INSERT INTO "Profession" ("id", "name", "category", "icon") VALUES
  (gen_random_uuid()::text, 'Dasturchi', 'IT & Texnologiya', '💻'),
  (gen_random_uuid()::text, 'Sun''iy Intellekt mutaxassisi', 'IT & Texnologiya', '🤖'),
  (gen_random_uuid()::text, 'Kiberxavfsizlik mutaxassisi', 'IT & Texnologiya', '🛡️'),
  (gen_random_uuid()::text, 'Grafik Dizayner', 'IT & Texnologiya', '🎨'),
  (gen_random_uuid()::text, 'Mobil ilova yaratuvchi', 'IT & Texnologiya', '📱'),
  (gen_random_uuid()::text, 'O''yin yaratuvchi', 'IT & Texnologiya', '🎮'),
  (gen_random_uuid()::text, 'Veb-dasturchi', 'IT & Texnologiya', '🌐'),
  (gen_random_uuid()::text, 'Ma''lumotlar tahlilchisi', 'IT & Texnologiya', '📊'),
  (gen_random_uuid()::text, 'Tarmoq muhandisi', 'IT & Texnologiya', '🕸️'),
  (gen_random_uuid()::text, 'Robototexnik', 'IT & Texnologiya', '🦾'),
  (gen_random_uuid()::text, '3D modelchi', 'IT & Texnologiya', '🧊'),
  (gen_random_uuid()::text, 'Dastur sinovchisi (QA)', 'IT & Texnologiya', '🐞'),
  (gen_random_uuid()::text, 'Kompyuter ustasi', 'IT & Texnologiya', '🔌'),
  (gen_random_uuid()::text, 'Dron uchuvchisi', 'IT & Texnologiya', '🚁'),
  (gen_random_uuid()::text, 'Shifokor', 'Tibbiyot', '🩺'),
  (gen_random_uuid()::text, 'Jarroh', 'Tibbiyot', '🏥'),
  (gen_random_uuid()::text, 'Stomatolog', 'Tibbiyot', '🦷'),
  (gen_random_uuid()::text, 'Hamshira', 'Tibbiyot', '💉'),
  (gen_random_uuid()::text, 'Psixolog', 'Tibbiyot', '🧠'),
  (gen_random_uuid()::text, 'Farmatsevt', 'Tibbiyot', '💊'),
  (gen_random_uuid()::text, 'Veterinar', 'Tibbiyot', '🐾'),
  (gen_random_uuid()::text, 'Pediatr', 'Tibbiyot', '👶'),
  (gen_random_uuid()::text, 'Kardiolog', 'Tibbiyot', '❤️'),
  (gen_random_uuid()::text, 'Ko''z shifokori', 'Tibbiyot', '👁️'),
  (gen_random_uuid()::text, 'Laborant', 'Tibbiyot', '🧪'),
  (gen_random_uuid()::text, 'Rentgenolog', 'Tibbiyot', '📡'),
  (gen_random_uuid()::text, 'Tez yordam feldsheri', 'Tibbiyot', '🚑'),
  (gen_random_uuid()::text, 'Reabilitolog', 'Tibbiyot', '🦯'),
  (gen_random_uuid()::text, 'Dietolog', 'Tibbiyot', '🍎'),
  (gen_random_uuid()::text, 'O''qituvchi', 'Ta''lim & Ilm', '📚'),
  (gen_random_uuid()::text, 'Olim', 'Ta''lim & Ilm', '🔬'),
  (gen_random_uuid()::text, 'Tarbiyachi', 'Ta''lim & Ilm', '🧸'),
  (gen_random_uuid()::text, 'Boshlang''ich sinf o''qituvchisi', 'Ta''lim & Ilm', '✏️'),
  (gen_random_uuid()::text, 'Maktab direktori', 'Ta''lim & Ilm', '🏫'),
  (gen_random_uuid()::text, 'Kutubxonachi', 'Ta''lim & Ilm', '📖'),
  (gen_random_uuid()::text, 'Tarjimon', 'Ta''lim & Ilm', '🗣️'),
  (gen_random_uuid()::text, 'Arxeolog', 'Ta''lim & Ilm', '⛏️'),
  (gen_random_uuid()::text, 'Geolog', 'Ta''lim & Ilm', '🏔️'),
  (gen_random_uuid()::text, 'Astronom', 'Ta''lim & Ilm', '🔭'),
  (gen_random_uuid()::text, 'Matematik', 'Ta''lim & Ilm', '➗'),
  (gen_random_uuid()::text, 'Biolog', 'Ta''lim & Ilm', '🧬'),
  (gen_random_uuid()::text, 'Tarixchi', 'Ta''lim & Ilm', '📜'),
  (gen_random_uuid()::text, 'Harbiy xizmatchi', 'Harbiy & Huquq', '🎖️'),
  (gen_random_uuid()::text, 'IIB xodimi', 'Harbiy & Huquq', '👮'),
  (gen_random_uuid()::text, 'Huquqshunos', 'Harbiy & Huquq', '⚖️'),
  (gen_random_uuid()::text, 'Qutqaruvchi (FVV)', 'Harbiy & Huquq', '🚒'),
  (gen_random_uuid()::text, 'Chegarachi', 'Harbiy & Huquq', '🚩'),
  (gen_random_uuid()::text, 'Sudya', 'Harbiy & Huquq', '🔨'),
  (gen_random_uuid()::text, 'Prokuror', 'Harbiy & Huquq', '📕'),
  (gen_random_uuid()::text, 'Advokat', 'Harbiy & Huquq', '📗'),
  (gen_random_uuid()::text, 'Tergovchi', 'Harbiy & Huquq', '🔍'),
  (gen_random_uuid()::text, 'Xavfsizlik xodimi', 'Harbiy & Huquq', '🛡️'),
  (gen_random_uuid()::text, 'Harbiy shifokor', 'Harbiy & Huquq', '⚕️'),
  (gen_random_uuid()::text, 'Notarius', 'Harbiy & Huquq', '🖋️'),
  (gen_random_uuid()::text, 'Bojxona xodimi', 'Harbiy & Huquq', '📦'),
  (gen_random_uuid()::text, 'Muhandis', 'Muhandislik', '⚙️'),
  (gen_random_uuid()::text, 'Arxitektor', 'Muhandislik', '🏗️'),
  (gen_random_uuid()::text, 'Quruvchi', 'Muhandislik', '👷'),
  (gen_random_uuid()::text, 'Elektrchi', 'Muhandislik', '💡'),
  (gen_random_uuid()::text, 'Uchuvchi', 'Muhandislik', '✈️'),
  (gen_random_uuid()::text, 'Payvandchi', 'Muhandislik', '🔥'),
  (gen_random_uuid()::text, 'Santexnik', 'Muhandislik', '🔧'),
  (gen_random_uuid()::text, 'Avtomobil ustasi', 'Muhandislik', '🚗'),
  (gen_random_uuid()::text, 'Energetik', 'Muhandislik', '🔋'),
  (gen_random_uuid()::text, 'Neft va gaz muhandisi', 'Muhandislik', '⛽'),
  (gen_random_uuid()::text, 'Kon muhandisi', 'Muhandislik', '⛏️'),
  (gen_random_uuid()::text, 'Konstruktor', 'Muhandislik', '📐'),
  (gen_random_uuid()::text, 'Suv xo''jaligi muhandisi', 'Muhandislik', '🌊'),
  (gen_random_uuid()::text, 'Yo''l qurilishi muhandisi', 'Muhandislik', '🚧'),
  (gen_random_uuid()::text, 'Iqlim texnikasi ustasi', 'Muhandislik', '❄️'),
  (gen_random_uuid()::text, 'Rassom', 'Ijodkorlik', '🖌️'),
  (gen_random_uuid()::text, 'Musiqachi', 'Ijodkorlik', '🎵'),
  (gen_random_uuid()::text, 'Jurnalist', 'Ijodkorlik', '🎤'),
  (gen_random_uuid()::text, 'Bloger/Youtuber', 'Ijodkorlik', '🎥'),
  (gen_random_uuid()::text, 'Oshpaz', 'Ijodkorlik', '👨‍🍳'),
  (gen_random_uuid()::text, 'Tikuvchi/Dizayner', 'Ijodkorlik', '✂️'),
  (gen_random_uuid()::text, 'Fotograf', 'Ijodkorlik', '📷'),
  (gen_random_uuid()::text, 'Video montajchi', 'Ijodkorlik', '🎬'),
  (gen_random_uuid()::text, 'Aktyor', 'Ijodkorlik', '🎭'),
  (gen_random_uuid()::text, 'Rejissyor', 'Ijodkorlik', '🎞️'),
  (gen_random_uuid()::text, 'Yozuvchi/Shoir', 'Ijodkorlik', '🖊️'),
  (gen_random_uuid()::text, 'Xonanda', 'Ijodkorlik', '🎙️'),
  (gen_random_uuid()::text, 'Raqqosa', 'Ijodkorlik', '💃'),
  (gen_random_uuid()::text, 'Interyer dizayneri', 'Ijodkorlik', '🛋️'),
  (gen_random_uuid()::text, 'Animator', 'Ijodkorlik', '✨'),
  (gen_random_uuid()::text, 'Ovoz rejissyori', 'Ijodkorlik', '🔊'),
  (gen_random_uuid()::text, 'SMM mutaxassisi', 'Ijodkorlik', '📣'),
  (gen_random_uuid()::text, 'Fermer', 'Tadbirkorlik', '🚜'),
  (gen_random_uuid()::text, 'Tadbirkor', 'Tadbirkorlik', '💼'),
  (gen_random_uuid()::text, 'Bank xodimi', 'Tadbirkorlik', '🏦'),
  (gen_random_uuid()::text, 'Sportchi/Murabbiy', 'Tadbirkorlik', '⚽'),
  (gen_random_uuid()::text, 'Buxgalter', 'Tadbirkorlik', '🧮'),
  (gen_random_uuid()::text, 'Iqtisodchi', 'Tadbirkorlik', '📈'),
  (gen_random_uuid()::text, 'Marketolog', 'Tadbirkorlik', '🎯'),
  (gen_random_uuid()::text, 'Menejer', 'Tadbirkorlik', '📋'),
  (gen_random_uuid()::text, 'Savdo mutaxassisi', 'Tadbirkorlik', '🛒'),
  (gen_random_uuid()::text, 'Auditor', 'Tadbirkorlik', '🗂️'),
  (gen_random_uuid()::text, 'Sug''urta agenti', 'Tadbirkorlik', '📄'),
  (gen_random_uuid()::text, 'Investor', 'Tadbirkorlik', '🐖'),
  (gen_random_uuid()::text, 'Loyiha rahbari', 'Tadbirkorlik', '✅'),
  (gen_random_uuid()::text, 'Agronom', 'Qishloq xo''jaligi', '🌱'),
  (gen_random_uuid()::text, 'Chorvador', 'Qishloq xo''jaligi', '🐄'),
  (gen_random_uuid()::text, 'Bog''bon', 'Qishloq xo''jaligi', '🌳'),
  (gen_random_uuid()::text, 'Pillachi', 'Qishloq xo''jaligi', '🐛'),
  (gen_random_uuid()::text, 'Asalarichi', 'Qishloq xo''jaligi', '🍯'),
  (gen_random_uuid()::text, 'Paxtakor', 'Qishloq xo''jaligi', '🌸'),
  (gen_random_uuid()::text, 'Sabzavotchi', 'Qishloq xo''jaligi', '🥕'),
  (gen_random_uuid()::text, 'Mexanizator', 'Qishloq xo''jaligi', '🚜'),
  (gen_random_uuid()::text, 'Suv xo''jaligi mutaxassisi', 'Qishloq xo''jaligi', '💧'),
  (gen_random_uuid()::text, 'Baliqchi', 'Qishloq xo''jaligi', '🐟'),
  (gen_random_uuid()::text, 'Parrandachi', 'Qishloq xo''jaligi', '🥚'),
  (gen_random_uuid()::text, 'Zootexnik', 'Qishloq xo''jaligi', '🐓'),
  (gen_random_uuid()::text, 'Issiqxona egasi', 'Qishloq xo''jaligi', '🏡'),
  (gen_random_uuid()::text, 'Don va g''alla mutaxassisi', 'Qishloq xo''jaligi', '🌾'),
  (gen_random_uuid()::text, 'Haydovchi', 'Transport & Logistika', '🚙'),
  (gen_random_uuid()::text, 'Yuk mashinasi haydovchisi', 'Transport & Logistika', '🚚'),
  (gen_random_uuid()::text, 'Temiryo''l mashinisti', 'Transport & Logistika', '🚆'),
  (gen_random_uuid()::text, 'Avtobus haydovchisi', 'Transport & Logistika', '🚌'),
  (gen_random_uuid()::text, 'Taksi haydovchisi', 'Transport & Logistika', '🚕'),
  (gen_random_uuid()::text, 'Logistika menejeri', 'Transport & Logistika', '📦'),
  (gen_random_uuid()::text, 'Ombor mudiri', 'Transport & Logistika', '🗃️'),
  (gen_random_uuid()::text, 'Kuryer', 'Transport & Logistika', '🚲'),
  (gen_random_uuid()::text, 'Dispetcher', 'Transport & Logistika', '🎧'),
  (gen_random_uuid()::text, 'Aviatsiya texnigi', 'Transport & Logistika', '🛫'),
  (gen_random_uuid()::text, 'Yuk qabul qiluvchi', 'Transport & Logistika', '📝'),
  (gen_random_uuid()::text, 'Ofitsiant', 'Xizmat ko''rsatish', '🍽️'),
  (gen_random_uuid()::text, 'Barista', 'Xizmat ko''rsatish', '☕'),
  (gen_random_uuid()::text, 'Qandolatchi', 'Xizmat ko''rsatish', '🍰'),
  (gen_random_uuid()::text, 'Novvoy', 'Xizmat ko''rsatish', '🥐'),
  (gen_random_uuid()::text, 'Sartarosh', 'Xizmat ko''rsatish', '💈'),
  (gen_random_uuid()::text, 'Kosmetolog', 'Xizmat ko''rsatish', '💎'),
  (gen_random_uuid()::text, 'Mehmonxona administratori', 'Xizmat ko''rsatish', '🛏️'),
  (gen_random_uuid()::text, 'Gid (yo''lboshchi)', 'Xizmat ko''rsatish', '🗺️'),
  (gen_random_uuid()::text, 'Turizm menejeri', 'Xizmat ko''rsatish', '🧳'),
  (gen_random_uuid()::text, 'Sotuvchi', 'Xizmat ko''rsatish', '🏪'),
  (gen_random_uuid()::text, 'Kassir', 'Xizmat ko''rsatish', '💳'),
  (gen_random_uuid()::text, 'Tozalash xizmati xodimi', 'Xizmat ko''rsatish', '🧴'),
  (gen_random_uuid()::text, 'Davlat xizmatchisi', 'Davlat xizmati', '🏛️'),
  (gen_random_uuid()::text, 'Hokim yordamchisi', 'Davlat xizmati', '🏢'),
  (gen_random_uuid()::text, 'Mahalla raisi', 'Davlat xizmati', '👥'),
  (gen_random_uuid()::text, 'Diplomat', 'Davlat xizmati', '🌍'),
  (gen_random_uuid()::text, 'Statistik', 'Davlat xizmati', '📉'),
  (gen_random_uuid()::text, 'Soliq inspektori', 'Davlat xizmati', '🧾'),
  (gen_random_uuid()::text, 'Ijtimoiy xodim', 'Davlat xizmati', '🤝'),
  (gen_random_uuid()::text, 'Ekolog', 'Davlat xizmati', '🍃'),
  (gen_random_uuid()::text, 'Arxivchi', 'Davlat xizmati', '🗄️'),
  (gen_random_uuid()::text, 'Pochta xodimi', 'Davlat xizmati', '✉️'),
  (gen_random_uuid()::text, 'FHDYo xodimi', 'Davlat xizmati', '📃')
ON CONFLICT ("name") DO NOTHING;

UPDATE "Profession" AS p
SET "category" = v."category", "icon" = v."icon"
FROM (VALUES
  ('Dasturchi', 'IT & Texnologiya', '💻'),
  ('Sun''iy Intellekt mutaxassisi', 'IT & Texnologiya', '🤖'),
  ('Kiberxavfsizlik mutaxassisi', 'IT & Texnologiya', '🛡️'),
  ('Grafik Dizayner', 'IT & Texnologiya', '🎨'),
  ('Mobil ilova yaratuvchi', 'IT & Texnologiya', '📱'),
  ('O''yin yaratuvchi', 'IT & Texnologiya', '🎮'),
  ('Veb-dasturchi', 'IT & Texnologiya', '🌐'),
  ('Ma''lumotlar tahlilchisi', 'IT & Texnologiya', '📊'),
  ('Tarmoq muhandisi', 'IT & Texnologiya', '🕸️'),
  ('Robototexnik', 'IT & Texnologiya', '🦾'),
  ('3D modelchi', 'IT & Texnologiya', '🧊'),
  ('Dastur sinovchisi (QA)', 'IT & Texnologiya', '🐞'),
  ('Kompyuter ustasi', 'IT & Texnologiya', '🔌'),
  ('Dron uchuvchisi', 'IT & Texnologiya', '🚁'),
  ('Shifokor', 'Tibbiyot', '🩺'),
  ('Jarroh', 'Tibbiyot', '🏥'),
  ('Stomatolog', 'Tibbiyot', '🦷'),
  ('Hamshira', 'Tibbiyot', '💉'),
  ('Psixolog', 'Tibbiyot', '🧠'),
  ('Farmatsevt', 'Tibbiyot', '💊'),
  ('Veterinar', 'Tibbiyot', '🐾'),
  ('Pediatr', 'Tibbiyot', '👶'),
  ('Kardiolog', 'Tibbiyot', '❤️'),
  ('Ko''z shifokori', 'Tibbiyot', '👁️'),
  ('Laborant', 'Tibbiyot', '🧪'),
  ('Rentgenolog', 'Tibbiyot', '📡'),
  ('Tez yordam feldsheri', 'Tibbiyot', '🚑'),
  ('Reabilitolog', 'Tibbiyot', '🦯'),
  ('Dietolog', 'Tibbiyot', '🍎'),
  ('O''qituvchi', 'Ta''lim & Ilm', '📚'),
  ('Olim', 'Ta''lim & Ilm', '🔬'),
  ('Tarbiyachi', 'Ta''lim & Ilm', '🧸'),
  ('Boshlang''ich sinf o''qituvchisi', 'Ta''lim & Ilm', '✏️'),
  ('Maktab direktori', 'Ta''lim & Ilm', '🏫'),
  ('Kutubxonachi', 'Ta''lim & Ilm', '📖'),
  ('Tarjimon', 'Ta''lim & Ilm', '🗣️'),
  ('Arxeolog', 'Ta''lim & Ilm', '⛏️'),
  ('Geolog', 'Ta''lim & Ilm', '🏔️'),
  ('Astronom', 'Ta''lim & Ilm', '🔭'),
  ('Matematik', 'Ta''lim & Ilm', '➗'),
  ('Biolog', 'Ta''lim & Ilm', '🧬'),
  ('Tarixchi', 'Ta''lim & Ilm', '📜'),
  ('Harbiy xizmatchi', 'Harbiy & Huquq', '🎖️'),
  ('IIB xodimi', 'Harbiy & Huquq', '👮'),
  ('Huquqshunos', 'Harbiy & Huquq', '⚖️'),
  ('Qutqaruvchi (FVV)', 'Harbiy & Huquq', '🚒'),
  ('Chegarachi', 'Harbiy & Huquq', '🚩'),
  ('Sudya', 'Harbiy & Huquq', '🔨'),
  ('Prokuror', 'Harbiy & Huquq', '📕'),
  ('Advokat', 'Harbiy & Huquq', '📗'),
  ('Tergovchi', 'Harbiy & Huquq', '🔍'),
  ('Xavfsizlik xodimi', 'Harbiy & Huquq', '🛡️'),
  ('Harbiy shifokor', 'Harbiy & Huquq', '⚕️'),
  ('Notarius', 'Harbiy & Huquq', '🖋️'),
  ('Bojxona xodimi', 'Harbiy & Huquq', '📦'),
  ('Muhandis', 'Muhandislik', '⚙️'),
  ('Arxitektor', 'Muhandislik', '🏗️'),
  ('Quruvchi', 'Muhandislik', '👷'),
  ('Elektrchi', 'Muhandislik', '💡'),
  ('Uchuvchi', 'Muhandislik', '✈️'),
  ('Payvandchi', 'Muhandislik', '🔥'),
  ('Santexnik', 'Muhandislik', '🔧'),
  ('Avtomobil ustasi', 'Muhandislik', '🚗'),
  ('Energetik', 'Muhandislik', '🔋'),
  ('Neft va gaz muhandisi', 'Muhandislik', '⛽'),
  ('Kon muhandisi', 'Muhandislik', '⛏️'),
  ('Konstruktor', 'Muhandislik', '📐'),
  ('Suv xo''jaligi muhandisi', 'Muhandislik', '🌊'),
  ('Yo''l qurilishi muhandisi', 'Muhandislik', '🚧'),
  ('Iqlim texnikasi ustasi', 'Muhandislik', '❄️'),
  ('Rassom', 'Ijodkorlik', '🖌️'),
  ('Musiqachi', 'Ijodkorlik', '🎵'),
  ('Jurnalist', 'Ijodkorlik', '🎤'),
  ('Bloger/Youtuber', 'Ijodkorlik', '🎥'),
  ('Oshpaz', 'Ijodkorlik', '👨‍🍳'),
  ('Tikuvchi/Dizayner', 'Ijodkorlik', '✂️'),
  ('Fotograf', 'Ijodkorlik', '📷'),
  ('Video montajchi', 'Ijodkorlik', '🎬'),
  ('Aktyor', 'Ijodkorlik', '🎭'),
  ('Rejissyor', 'Ijodkorlik', '🎞️'),
  ('Yozuvchi/Shoir', 'Ijodkorlik', '🖊️'),
  ('Xonanda', 'Ijodkorlik', '🎙️'),
  ('Raqqosa', 'Ijodkorlik', '💃'),
  ('Interyer dizayneri', 'Ijodkorlik', '🛋️'),
  ('Animator', 'Ijodkorlik', '✨'),
  ('Ovoz rejissyori', 'Ijodkorlik', '🔊'),
  ('SMM mutaxassisi', 'Ijodkorlik', '📣'),
  ('Fermer', 'Tadbirkorlik', '🚜'),
  ('Tadbirkor', 'Tadbirkorlik', '💼'),
  ('Bank xodimi', 'Tadbirkorlik', '🏦'),
  ('Sportchi/Murabbiy', 'Tadbirkorlik', '⚽'),
  ('Buxgalter', 'Tadbirkorlik', '🧮'),
  ('Iqtisodchi', 'Tadbirkorlik', '📈'),
  ('Marketolog', 'Tadbirkorlik', '🎯'),
  ('Menejer', 'Tadbirkorlik', '📋'),
  ('Savdo mutaxassisi', 'Tadbirkorlik', '🛒'),
  ('Auditor', 'Tadbirkorlik', '🗂️'),
  ('Sug''urta agenti', 'Tadbirkorlik', '📄'),
  ('Investor', 'Tadbirkorlik', '🐖'),
  ('Loyiha rahbari', 'Tadbirkorlik', '✅'),
  ('Agronom', 'Qishloq xo''jaligi', '🌱'),
  ('Chorvador', 'Qishloq xo''jaligi', '🐄'),
  ('Bog''bon', 'Qishloq xo''jaligi', '🌳'),
  ('Pillachi', 'Qishloq xo''jaligi', '🐛'),
  ('Asalarichi', 'Qishloq xo''jaligi', '🍯'),
  ('Paxtakor', 'Qishloq xo''jaligi', '🌸'),
  ('Sabzavotchi', 'Qishloq xo''jaligi', '🥕'),
  ('Mexanizator', 'Qishloq xo''jaligi', '🚜'),
  ('Suv xo''jaligi mutaxassisi', 'Qishloq xo''jaligi', '💧'),
  ('Baliqchi', 'Qishloq xo''jaligi', '🐟'),
  ('Parrandachi', 'Qishloq xo''jaligi', '🥚'),
  ('Zootexnik', 'Qishloq xo''jaligi', '🐓'),
  ('Issiqxona egasi', 'Qishloq xo''jaligi', '🏡'),
  ('Don va g''alla mutaxassisi', 'Qishloq xo''jaligi', '🌾'),
  ('Haydovchi', 'Transport & Logistika', '🚙'),
  ('Yuk mashinasi haydovchisi', 'Transport & Logistika', '🚚'),
  ('Temiryo''l mashinisti', 'Transport & Logistika', '🚆'),
  ('Avtobus haydovchisi', 'Transport & Logistika', '🚌'),
  ('Taksi haydovchisi', 'Transport & Logistika', '🚕'),
  ('Logistika menejeri', 'Transport & Logistika', '📦'),
  ('Ombor mudiri', 'Transport & Logistika', '🗃️'),
  ('Kuryer', 'Transport & Logistika', '🚲'),
  ('Dispetcher', 'Transport & Logistika', '🎧'),
  ('Aviatsiya texnigi', 'Transport & Logistika', '🛫'),
  ('Yuk qabul qiluvchi', 'Transport & Logistika', '📝'),
  ('Ofitsiant', 'Xizmat ko''rsatish', '🍽️'),
  ('Barista', 'Xizmat ko''rsatish', '☕'),
  ('Qandolatchi', 'Xizmat ko''rsatish', '🍰'),
  ('Novvoy', 'Xizmat ko''rsatish', '🥐'),
  ('Sartarosh', 'Xizmat ko''rsatish', '💈'),
  ('Kosmetolog', 'Xizmat ko''rsatish', '💎'),
  ('Mehmonxona administratori', 'Xizmat ko''rsatish', '🛏️'),
  ('Gid (yo''lboshchi)', 'Xizmat ko''rsatish', '🗺️'),
  ('Turizm menejeri', 'Xizmat ko''rsatish', '🧳'),
  ('Sotuvchi', 'Xizmat ko''rsatish', '🏪'),
  ('Kassir', 'Xizmat ko''rsatish', '💳'),
  ('Tozalash xizmati xodimi', 'Xizmat ko''rsatish', '🧴'),
  ('Davlat xizmatchisi', 'Davlat xizmati', '🏛️'),
  ('Hokim yordamchisi', 'Davlat xizmati', '🏢'),
  ('Mahalla raisi', 'Davlat xizmati', '👥'),
  ('Diplomat', 'Davlat xizmati', '🌍'),
  ('Statistik', 'Davlat xizmati', '📉'),
  ('Soliq inspektori', 'Davlat xizmati', '🧾'),
  ('Ijtimoiy xodim', 'Davlat xizmati', '🤝'),
  ('Ekolog', 'Davlat xizmati', '🍃'),
  ('Arxivchi', 'Davlat xizmati', '🗄️'),
  ('Pochta xodimi', 'Davlat xizmati', '✉️'),
  ('FHDYo xodimi', 'Davlat xizmati', '📃')
) AS v("name", "category", "icon")
WHERE p."name" = v."name"
  AND (p."category" IS DISTINCT FROM v."category" OR p."icon" IS DISTINCT FROM v."icon");

SELECT
  (SELECT count(*) FROM "Profession") AS jami_kasblar,
  (SELECT count(DISTINCT "category") FROM "Profession") AS yonalishlar;
